apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  rules:
  - host: hello-node.lh
    http:
      paths:
      - backend:
          serviceName: hello-node
          servicePort: 80
