apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry
  namespace: system-tools
  labels:
    app: docker-registry
spec:
  tls:
  - hosts:
    - docker.k8s
    secretName: docker-registry-tls
  rules:
  - host: docker.k8s
    http:
      paths:
      - backend:
          serviceName: docker-registry
          servicePort: 5000
