apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: system-tools
  labels:
    app: docker-registry
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: docker-registry
