---
apiVersion: v1
kind: ReplicationController
metadata:
  name: samba-server
  namespace: system-tools
  labels:
    app: samba-server
spec:
  replicas: 1
  selector:
    app: samba-server
  template:
    metadata:
      name: samba-server
      labels:
        app: samba-server
    spec:
      containers:
      - name: samba
        image: lcr.lh/samba
        ports:
        - protocol: UDP
          containerPort: 137
          hostPort: 137
        - protocol: UDP
          containerPort: 138
          hostPort: 138
        - protocol: TCP
          containerPort: 139
          hostPort: 139
        - protocol: TCP
          containerPort: 445
          hostPort: 445
        args: ["-u kubernetes;password", "-s host-storage;/mnt/host-storage;yes;no;no;kubernetes"]
        volumeMounts:
        - mountPath: /mnt/host-storage
          name: host-storage
      volumes:
      - name: host-storage
        hostPath:
          path: /mnt/host-storage
