---
apiVersion: v1
kind: ReplicationController
metadata:
  name: samba-server
  namespace: system-tools
  labels:
    app: samba-server
spec:
  replicas: 1
  selector:
    app: samba-server
  template:
    metadata:
      name: samba-server
      labels:
        app: samba-server
    spec:
      hostNetwork: true
      volumes:
      - name: storage
        hostPath:
          path: /volumes
      containers:
      - name: samba
        image: docker.k8s/samba
        imagePullPolicy: Always
        ports:
        - protocol: UDP
          containerPort: 137
          hostPort: 137
        - protocol: UDP
          containerPort: 138
          hostPort: 138
        - protocol: TCP
          containerPort: 139
          hostPort: 139
        - protocol: TCP
          containerPort: 445
          hostPort: 445
        args: ["-u kubernetes;kubernetes", "-s volumes;/volumes;yes;no;no;kubernetes"]
        volumeMounts:
        - name: storage
          mountPath: /volumes
