---
apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: system-tools
  labels:
    app: default-backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: default-backend
