---
apiVersion: v1
kind: ReplicationController
metadata:
  name: default-backend
  namespace: system-tools
  labels:
    app: default-backend
spec:
  replicas: 1
  selector:
    app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          hostPort: 32443
