---
apiVersion: v1
kind: ReplicationController
metadata:
  name: default-backend
  namespace: system-tools
  labels:
    app: default-backend
spec:
  replicas: 1
  selector:
    app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
