---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress
  namespace: system-tools
  labels:
    app: nginx-ingress
data:
  body-size: 4096m
  proxy-buffer-size: 256k
  custom-errors: "false"
