---
apiVersion: v1
kind: Pod
metadata:
  name: node-script
  labels:
    app: node-script
spec:
  containers:
    - name: node
      image: node:4.4
      volumeMounts:
      - name: node-script
        mountPath: /usr/src/app
      command:
        - sleep
        - "3600"
  restartPolicy: Always
  volumes:
  - name: node-script
    hostPath:
      path: /mnt/host-storage/node-script
