apiVersion: v1
kind: ReplicationController
metadata:
  name: container-registry
  namespace: system-tools
  labels:
    app: container-registry
spec:
  replicas: 1
  selector:
    app: container-registry
  template:
    metadata:
      name: container-registry
      labels:
        app: container-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: STORAGE_PATH
          value: '/var/lib/registry'
        ports:
        - containerPort: 5000
          hostPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
      volumes:
      - name: registry-data
        hostPath:
          path: /var/lib/registry
