---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_PORT
          value: "3306"
        - name: PMA_HOST
          value: "127.0.0.1"
        - name: PHP_UPLOAD_MAX_FILESIZE
          value: "4096M"
      restartPolicy: Always
      volumes:
      - name: mysql
        hostPath:
          path: /mnt/host-storage/mysql
