---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: lcr.lh/hello-node
        ports:
        - containerPort: 8080
