mysql:
  container_name: "scope-mysql"
  hostname: "scope-mysql"
  restart: always
  image: mysql:5.6
  volumes:
    - ./.db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: euZKfAA9Fl2WGMRGH
    MYSQL_DATABASE: wp_dev
    MYSQL_USER:     wp_user
    MYSQL_PASSWORD: K_x0AdD7c<KlYeVR
    mem_limit: 128m

data:
  container_name: "scope-data"
  hostname: "scope-data"
  image: debian:stable
  restart: always
  volumes:
    - ./:/var/www/html/

php:
  container_name: "scope-php"
  hostname: "scope-php"
  restart: always
  build: ./docker/php
  volumes_from:
    - data
  links:
    - mysql:db
  dns:
    - 8.8.8.8
    - 8.8.4.4

backend:
  container_name: "scope"
  hostname: "scope"
  restart: always
  build: ./docker/backend
  volumes_from:
    - data
  links:
    - php:php
  ports:
    - "80:80"
  dns:
    - 8.8.8.8
    - 8.8.4.4

gulp:
  container_name: "scope-gulp"
  hostname: "scope-gulp"
  restart: always
  build: ./docker/gulp
  volumes_from:
    - data

#capistrano:
#  container_name: "scope-capistrano"
#  hostname: "scope-capistrano"
#  build: ./docker/capistrano
#  restart: always
#  command: /script/start
#  volumes:
#    - $SSH_AUTH_SOCK:/tmp/agent.sock
#  environment:
#    - SSH_AUTH_SOCK=/tmp/agent.sock
#  volumes_from:
#    - data
#
#phpmyadmin:
#  container_name: "scope-phpmyadmin"
#  hostname: "scope-phpmyadmin"
#  image: phpmyadmin/phpmyadmin
#  restart: always
#  ports:
#   - "8080:80"
#  links:
#    - mysql