apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lamp
  namespace: default
  labels:
    app: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp
  template:
    metadata:
      labels:
        app: lamp
    spec:
      containers:
      - name: nginx
        image: localhost:30000/lamp-nginx:1.9r2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: php
        image: localhost:30000/lamp-php:1.9r1
        imagePullPolicy: IfNotPresent
        ports:
        - name: php-fpm
          containerPort: 9000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lamp
  labels:
    app: lamp
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: lamp
